### PR TITLE
Update introduction tutorial.

### PR DESCRIPTION
**Pull request by dakotablair**
Hello! My name is Dakota, and I work with @matthewcarbone and am preparing to present this tutorial later this summer.

This PR offers some changes to the original that I would ask you to include. I have added some more detailed "asides" in places, reworked much of the prose, updated some code examples and moved some sections to the end. The asides are optional sections which dive deep into a topic which is otherwise not covered in the tutorial. I moved instructions regarding package installation to the end, along with adding instructions on how to install python itself. Many of these changes come from [another tutorial](https://github.com/matthewcarbone/AIML-tutorials/blob/master/notebooks/legacy/000_Python.ipynb) I gave previously on a similar topic.

I think it would be useful to discuss objectives for the conda portion and make that section more detailed, but I think it makes sense to have it at the end since Colab includes all the packages in the rest of the tutorial.

Let me know what you think!

P.S. It may be easiest to preview the changes [in Colab](https://drive.google.com/file/d/10ptJ_Zb1X5PzhQMv6evxSwfK5AVpcBxD/view?usp=sharing).

### CODE REVIEW

**Comment by voetberg** [comment]
Dakota, this all looks great!!! thank you for cleaning up the places where I still had placeholders as well. You really make some great improvements. I'll mark approval but let Matt decide if it's time to merge this in.

**Review by voetberg — APPROVED** [review]

**Comment by matthewcarbone** [comment]
@voetberg I agree the changes are fantastic. @dakotablair I'm good to merge this whenever you think its ready!

**Comment by dakotablair** [comment]
It's ready to merge as-is, but I think it would be good to add more conda environment content, but that can wait for a future pull request. I'm open to any and all suggestions!

**Comment by matthewcarbone** [comment]
@dakotablair Agreed. Merging now!

**Pull request merged**
